// Execution Analytics Types - Verified vs Generated

// Verified (deterministic):
// - semantic_query: from a pre-defined semantic layer
// - omni_query: from a pre-defined integration (OmniQuery)
// - workflow: workflow defined inline in agent config
//
// Not Verified (generated by LLM):
// - sql_generated: SQL generated by LLM (sql: None)
// - agent_tool: agent tool defined as an asset/artifact in the agent

export type ExecutionType =
  | "semantic_query"
  | "omni_query"
  | "sql_generated"
  | "workflow"
  | "agent_tool";

export type ExecutionCategory = "verified" | "generated";

export interface ExecutionTypeInfo {
  type: ExecutionType;
  label: string;
  shortLabel: string;
  category: ExecutionCategory;
  color: string;
  chartColor: string;
  bgColor: string;
  borderColor: string;
  description: string;
}

export const EXECUTION_TYPES: Record<ExecutionType, ExecutionTypeInfo> = {
  semantic_query: {
    type: "semantic_query",
    label: "Semantic Query",
    shortLabel: "Semantic",
    category: "verified",
    color: "text-amber-400",
    chartColor: "#fbbf24",
    bgColor: "bg-amber-500/10",
    borderColor: "border-amber-500/20",
    description: "Pre-defined semantic layer query",
  },
  omni_query: {
    type: "omni_query",
    label: "OmniQuery",
    shortLabel: "OmniQuery",
    category: "verified",
    color: "text-cyan-400",
    chartColor: "#22d3ee",
    bgColor: "bg-cyan-500/10 border-cyan-500/20",
    borderColor: "border-cyan-500/20",
    description: "Pre-defined integration query",
  },
  workflow: {
    type: "workflow",
    label: "Workflow",
    shortLabel: "Workflow",
    category: "verified",
    color: "text-purple-400",
    chartColor: "#a78bfa",
    bgColor: "bg-purple-500/10",
    borderColor: "border-purple-500/20",
    description: "Workflow defined inline in agent config",
  },
  sql_generated: {
    type: "sql_generated",
    label: "LLM SQL",
    shortLabel: "LLM SQL",
    category: "generated",
    color: "text-orange-400",
    chartColor: "#fb923c",
    bgColor: "bg-orange-500/10 border-orange-500/20",
    borderColor: "border-orange-500/20",
    description: "SQL generated by LLM",
  },
  agent_tool: {
    type: "agent_tool",
    label: "Agent Tool",
    shortLabel: "Agent Tool",
    category: "generated",
    color: "text-blue-400",
    chartColor: "#60a5fa",
    bgColor: "bg-blue-500/10",
    borderColor: "border-blue-500/20",
    description: "Agent tool asset with LLM-generated response",
  },
};

export interface ExecutionSummary {
  totalExecutions: number;
  verifiedCount: number;
  generatedCount: number;
  verifiedPercent: number;
  generatedPercent: number;
  successRateVerified: number;
  successRateGenerated: number;
  mostExecutedType: string;
  // Breakdown by type
  semanticQueryCount: number;
  omniQueryCount: number;
  sqlGeneratedCount: number;
  workflowCount: number;
  agentToolCount: number;
}

export interface ExecutionTimeBucket {
  timestamp: string;
  verifiedCount: number;
  generatedCount: number;
  // Optional detailed breakdown
  semanticQueryCount?: number;
  omniQueryCount?: number;
  sqlGeneratedCount?: number;
  workflowCount?: number;
  agentToolCount?: number;
}

export interface AgentExecutionStats {
  agentRef: string;
  totalExecutions: number;
  verifiedCount: number;
  generatedCount: number;
  verifiedPercent: number;
  mostExecutedType: string;
  successRate: number;
}

export type SourceType = "agent" | "workflow";

export interface ExecutionDetail {
  traceId: string;
  spanId: string;
  timestamp: string;
  executionType: ExecutionType;
  isVerified: boolean;
  // Source information
  sourceType: SourceType;
  sourceRef: string;
  // Common fields
  status: "success" | "error";
  durationMs: number;
  database?: string;
  output?: string;
  error?: string;
  // Type-specific fields
  // For semantic queries
  topic?: string;
  semanticQueryParams?: string;
  generatedSql?: string;
  // For omni queries
  integration?: string;
  endpoint?: string;
  // For SQL queries (verified)
  sql?: string;
  sqlRef?: string;
  // For SQL queries (generated)
  userQuestion?: string;
  // For workflows
  workflowRef?: string;
  // For agent tools
  agentRef?: string;
  toolInput?: string;
}
