version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
  - package-ecosystem: "cargo"
    directories:
      - "/"
      - "/backend-workspaces"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 4
    allow:
      - dependency-type: "direct"
    groups: # here until https://github.com/dependabot/dependabot-core/issues/1778 is solved
      prod-cargo-minor-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-cargo-minor-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod-cargo-major-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
      dev-cargo-major-dependencies:
        dependency-type: "development"
        update-types:
          - "major"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    groups:
      prod-npm-minor-dependencies:
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      dev-npm-minor-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
      prod-npm-major-dependencies:
        dependency-type: "production"
        update-types:
          - "major"
      dev-npm-major-dependencies:
        dependency-type: "development"
        update-types:
          - "major"