repos:
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.35.1
  hooks:
  - id: yamllint
    args: [--format, parsable]
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
  rev: 0.2.3
  hooks:
  - id: yamlfmt
    args: [-m, "2", -s, "2", -o, "0", --width, '160', --implicit_start, --preserve-quotes]
    exclude: (.*/grafana_dashboards/.*)|(.*/alertmanager_rules/.*)|(.*/pnpm-lock.yaml)
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-json
    exclude: .*/.vscode/.*
  - id: pretty-format-json
    exclude: .*/.vscode/.*
    args:
    - "--autofix"
    - "--indent=2"
    - "--no-sort-keys"
