[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"

# enable changelog updates
changelog_update = true

# update dependencies with `cargo update`
dependencies_update = false

# create tags for the releases
git_tag_enable = true

# disable GitHub releases
git_release_enable = true

# labels for the release PR
pr_labels = ["release"]

# disallow updating repositories with uncommitted changes
allow_dirty = true

# disallow packaging with uncommitted changes
publish_allow_dirty = true
publish = false

# disable running `cargo-semver-checks`
semver_check = false

# disable running release for every commit
release_always = false

# support PR opened by release-please
pr_branch_prefix = "release-please-"