// A build script's submodules resolve beside build.rs, and `build/` is
// gitignored workspace-wide — hence a sibling file with an explicit path.
#[path = "build_route_catalog.rs"]
mod route_catalog;

fn main() {
    // Tell Cargo when to re-run this build script.
    // This prevents unnecessary rebuilds when just changing directories
    println!("cargo:rerun-if-env-changed=GITHUB_SHA");
    println!("cargo:rerun-if-env-changed=GITHUB_SERVER_URL");
    println!("cargo:rerun-if-env-changed=GITHUB_REPOSITORY");
    println!("cargo:rerun-if-env-changed=GITHUB_RUN_ID");
    println!("cargo:rerun-if-env-changed=FORCE_REBUILD");

    // Only rerun if build.rs itself changes
    println!("cargo:rerun-if-changed=build.rs");

    // Capture git commit hash from environment variable (set by CI)
    // Default to "dev" for local development builds
    let git_hash_long = std::env::var("GITHUB_SHA").unwrap_or_else(|_| "dev".to_string());

    // Short hash (first 7 chars)
    let git_hash = if git_hash_long.len() >= 7 {
        git_hash_long[..7].to_string()
    } else {
        git_hash_long.clone()
    };

    // Use a static timestamp for dev builds to avoid constant recompilation
    // In CI, use actual timestamp
    let build_timestamp = if std::env::var("CI").is_ok() || std::env::var("GITHUB_ACTIONS").is_ok()
    {
        chrono::Utc::now().to_rfc3339()
    } else {
        // Static timestamp for local dev to prevent rebuilds
        "dev-build".to_string()
    };

    let profile = std::env::var("PROFILE").unwrap_or_else(|_| "unknown".to_string());

    // Capture GitHub CI environment variables (if building in CI)
    let github_server_url = std::env::var("GITHUB_SERVER_URL").unwrap_or_default();
    let github_repository = std::env::var("GITHUB_REPOSITORY").unwrap_or_default();
    let github_run_id = std::env::var("GITHUB_RUN_ID").unwrap_or_default();

    // Set environment variables for use in the binary
    println!("cargo:rustc-env=GIT_HASH={}", git_hash);
    println!("cargo:rustc-env=GIT_HASH_LONG={}", git_hash_long);
    println!("cargo:rustc-env=BUILD_TIMESTAMP={}", build_timestamp);
    println!("cargo:rustc-env=BUILD_PROFILE={}", profile);
    println!("cargo:rustc-env=GITHUB_SERVER_URL={}", github_server_url);
    println!("cargo:rustc-env=GITHUB_REPOSITORY={}", github_repository);
    println!("cargo:rustc-env=GITHUB_RUN_ID={}", github_run_id);

    // `oxy api --routes` / `--help` list the whole HTTP surface. Axum has no
    // runtime route table, so the catalog is read out of the router source
    // here; `server::route_catalog` includes the result.
    emit_route_catalog();
}

/// Write `$OUT_DIR/route_catalog_generated.rs`: the endpoint table plus the
/// pre-rendered `--help` listing, so formatting it costs nothing at runtime
/// (clap builds every subcommand's help text on every `oxy` invocation).
fn emit_route_catalog() {
    let manifest_dir = std::path::PathBuf::from(
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is always set"),
    );
    // crates/app -> the workspace root.
    let repo_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .unwrap_or(&manifest_dir)
        .to_path_buf();
    println!("cargo:rerun-if-changed=build_route_catalog.rs");

    let routes = route_catalog::collect(&repo_root);

    let mut out = String::from(
        "// @generated by crates/app/build_route_catalog.rs — do not edit.\n\
         pub static GENERATED_ROUTES: &[GeneratedRoute] = &[\n",
    );
    for r in &routes {
        out.push_str(&format!(
            "    GeneratedRoute {{ method: {:?}, path: {:?}, handler: {:?}, surface: {:?}, description: {:?}, note: {:?} }},\n",
            r.method, r.path, r.handler, r.surface, r.description, r.note
        ));
    }
    out.push_str("];\n\n");
    out.push_str(&format!(
        "/// Pre-rendered route listing shown by `oxy api --help`.\npub static GENERATED_ROUTE_LISTING: &str = {:?};\n\n",
        route_catalog::render_listing(&routes)
    ));
    out.push_str("/// (surface id, display label, the credential it expects).\npub static GENERATED_SURFACES: &[(&str, &str, &str)] = &[\n");
    for (surface, label, credential) in route_catalog::SURFACES {
        out.push_str(&format!("    ({surface:?}, {label:?}, {credential:?}),\n"));
    }
    out.push_str("];\n\n");
    out.push_str(
        "/// Source trees the walker reads, with how many routes each one\n\
         /// contributed. Lets a test check both that nothing declaring routes was\n\
         /// left out of them, and that every listed tree is actually reached.\n\
         pub static GENERATED_SCANNED_DIRS: &[(&str, usize)] = &[\n",
    );
    for dir in route_catalog::SOURCE_DIRS {
        let contributed = routes.iter().filter(|r| r.source_dir == *dir).count();
        out.push_str(&format!("    ({dir:?}, {contributed}),\n"));
    }
    out.push_str("];\n");

    let dest = std::path::PathBuf::from(
        std::env::var("OUT_DIR").expect("OUT_DIR is always set for a build script"),
    )
    .join("route_catalog_generated.rs");
    std::fs::write(&dest, out).expect("write route catalog");
}
