name: sales_with_base
description: "Sales analysis with enforced base view for consistent join semantics"
base_view: orders
views:
  - orders
  - customers
  - products
default_filters:
  - field: "status"
    op: "not_in"
    value: ["cancelled", "refunded"]
