CREATE TABLE content_level_monthly_stats_fruits_veggies_csv("month" VARCHAR, property_grouping VARCHAR, property VARCHAR, content_type VARCHAR, content_id BIGINT, "views" VARCHAR, "minutes" VARCHAR);
CREATE TABLE customer_csv(id BIGINT, "name" VARCHAR, gender VARCHAR);
CREATE TABLE fruit_csv(id BIGINT, "name" VARCHAR, price BIGINT);
CREATE TABLE fruit_sales_csv(id BIGINT, fruit_id BIGINT, customer_id BIGINT, quantity BIGINT, amount BIGINT, date DATE);
CREATE TABLE fruit_suppliers_csv(id BIGINT, "name" VARCHAR, contact_email VARCHAR, contact_phone VARCHAR, country VARCHAR, rating DOUBLE);
CREATE TABLE fruit_supplier_relationships_csv(id BIGINT, fruit_id BIGINT, supplier_id BIGINT, wholesale_price DOUBLE, min_order_qty BIGINT, lead_time_days BIGINT, is_primary_supplier BOOLEAN);
CREATE TABLE large_csv("key" TIMESTAMP, fare_amount DOUBLE, pickup_datetime TIMESTAMP, pickup_longitude DOUBLE, pickup_latitude DOUBLE, dropoff_longitude DOUBLE, dropoff_latitude DOUBLE, passenger_count BIGINT);
CREATE TABLE monthly_active_user_by_platform_csv("month" VARCHAR, platform VARCHAR, users BIGINT);
CREATE TABLE monthly_revenue_by_region_csv("month" VARCHAR, region VARCHAR, revenue DOUBLE);
CREATE TABLE orders_csv(id BIGINT, customer_id BIGINT, shipping_address_id BIGINT, order_date DATE, status VARCHAR, total_amount DOUBLE, shipping_cost DOUBLE, tax_amount DOUBLE);
CREATE TABLE order_items_csv(order_id BIGINT, line_item_id BIGINT, product_id BIGINT, quantity BIGINT, unit_price BIGINT, discount_percent BIGINT);
CREATE TABLE order_returns_csv(return_id BIGINT, order_id BIGINT, line_item_id BIGINT, return_date DATE, reason VARCHAR, quantity BIGINT, refund_amount DOUBLE, status VARCHAR);
CREATE TABLE order_shipments_csv(shipment_id BIGINT, order_id BIGINT, line_item_id BIGINT, tracking_number VARCHAR, carrier VARCHAR, shipped_date DATE, estimated_delivery DATE, actual_delivery DATE, status VARCHAR);
CREATE TABLE shipping_addresses_csv(id BIGINT, customer_id BIGINT, address_line_1 VARCHAR, address_line_2 VARCHAR, city VARCHAR, state VARCHAR, postal_code VARCHAR, country VARCHAR, is_default BOOLEAN);
CREATE TABLE users_csv(user_id VARCHAR, user_name VARCHAR);
