//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "checkpoints")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub run_id: Uuid,
    pub replay_id: String,
    pub checkpoint_hash: String,
    pub output: Option<Json>,
    pub events: Option<Json>,
    pub child_run_info: Option<Json>,
    pub loop_values: Option<Json>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "run_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub runs: BelongsTo<super::runs::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
