//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod apalis_jobs;
pub mod api_keys;
pub mod artifacts;
pub mod branches;
pub mod checkpoints;
pub mod logs;
pub mod messages;
pub mod projects;
pub mod runs;
pub mod secrets;
pub mod settings;
pub mod tasks;
pub mod threads;
pub mod users;
pub mod workspace_users;
pub mod workspaces;
