//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

pub mod prelude;

pub mod apalis_jobs;
pub mod api_keys;
pub mod app_admins;
pub mod app_builds;
pub mod app_publish_tokens;
pub mod apps;
pub mod artifacts;
pub mod checkpoints;
pub mod custom_app_event;
pub mod custom_app_view_event;
pub mod customer_app_automation_runs;
/// Back-compat alias for the renamed `customer_app_automation_runs` module.
/// Procedures/Workflows were renamed to Automations; existing call sites
/// referencing `entity::customer_app_procedure_runs` keep resolving here.
pub use customer_app_automation_runs as customer_app_procedure_runs;
pub mod feature_flag;
pub mod git_namespaces;
pub mod github_accounts;
pub mod logs;
pub mod messages;
pub mod metric_anomalies;
pub mod org_billing;
pub mod org_invitations;
pub mod org_members;
pub mod org_secrets;
pub mod org_subdomains;
pub mod organizations;
pub mod quickbooks_oauth_states;
pub mod reconcile_configs;
pub mod run_sequences;
pub mod runs;
pub mod secrets;
pub mod settings;
pub mod slack_channel_defaults;
pub mod slack_installations;
pub mod slack_oauth_states;
pub mod slack_seen_events;
pub mod slack_threads;
pub mod slack_user_links;
pub mod slack_user_preferences;
pub mod stripe_webhook_events;
pub mod tasks;
pub mod test_case_human_verdicts;
pub mod test_project_runs;
pub mod test_run_cases;
pub mod test_run_sequences;
pub mod test_runs;
pub mod threads;
pub mod users;
pub mod workspace_health_state;
pub mod workspace_members;
pub mod workspace_oxy_access;
pub mod workspaces;

// ── compile boundary (Phase 1.6a) ────────────────────────────────────
pub mod agent_definitions;
pub mod airway_pipelines;
pub mod app_definitions;
pub mod automation_definitions;
/// Back-compat alias for the renamed `automation_definitions` module
/// (formerly `procedure_definitions`). Keeps existing
/// `entity::procedure_definitions::*` call sites resolving.
pub use automation_definitions as procedure_definitions;
pub mod compiled_references;
pub mod monitor_configs;
pub mod revisions;
pub mod semantic_topics;
pub mod semantic_views;
pub mod verified_queries;
pub mod workspace_compiled_configs;
pub mod world_model_configs;
