//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::conversations::Entity as Conversations;
pub use super::messages::Entity as Messages;
pub use super::tasks::Entity as Tasks;
pub use super::threads::Entity as Threads;
