//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::conversations::Entity as Conversations;
pub use super::messages::Entity as Messages;
pub use super::threads::Entity as Threads;
