//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use indexmap::IndexMap;
use sea_orm::{FromJsonQueryResult, entity::prelude::*, sea_query::IntoCondition};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Variables(pub IndexMap<String, Json>);

impl Variables {
    pub fn to_inner(self) -> IndexMap<String, Json> {
        self.0
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Output {
    pub task_name: String,
    #[serde(flatten)]
    pub output: Json,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub source_id: String,
    pub run_index: Option<i32>,
    pub root_source_id: Option<String>,
    pub root_run_index: Option<i32>,
    pub root_replay_ref: Option<String>,
    pub metadata: Option<Json>,
    pub children: Option<Json>,
    pub blocks: Option<Json>,
    pub variables: Option<Variables>,
    pub output: Option<Output>,
    pub error: Option<String>,
    pub project_id: Uuid,
    pub branch_id: Uuid,
    pub lookup_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::projects::Entity",
        from = "Column::ProjectId",
        to = "super::projects::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Projects,
    #[sea_orm(
        belongs_to = "super::messages::Entity",
        from = "Column::LookupId",
        to = "super::messages::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Messages,
}

impl Related<super::projects::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Projects.def()
    }
}

impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
