//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use indexmap::IndexMap;
use sea_orm::{FromJsonQueryResult, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Variables(pub IndexMap<String, Json>);

impl Variables {
    pub fn to_inner(self) -> IndexMap<String, Json> {
        self.0
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult)]
pub struct Output {
    pub task_name: String,
    #[serde(flatten)]
    pub output: Json,
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "runs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub source_id: String,
    pub run_index: Option<i32>,
    pub root_source_id: Option<String>,
    pub root_run_index: Option<i32>,
    pub root_replay_ref: Option<String>,
    pub metadata: Option<Json>,
    pub children: Option<Json>,
    pub blocks: Option<Json>,
    pub variables: Option<Variables>,
    pub output: Option<Output>,
    pub error: Option<String>,
    pub project_id: Uuid,
    pub branch_id: Uuid,
    pub lookup_id: Option<Uuid>,
    pub user_id: Option<Uuid>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<super::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        from = "lookup_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    pub messages: BelongsTo<Option<super::messages::Entity>>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
