//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::{JsonValue, entity::prelude::*};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "threads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub input: String,
    pub output: String,
    pub source: String,
    pub created_at: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Text")]
    pub references: String,
    pub source_type: String,
    pub user_id: Option<Uuid>,
    pub project_id: Uuid,
    pub is_processing: bool,
    #[sea_orm(column_type = "Json", nullable)]
    pub sandbox_info: Option<JsonValue>,
    #[sea_orm(has_many)]
    pub artifacts: HasMany<super::artifacts::Entity>,
    #[sea_orm(has_many)]
    pub logs: HasMany<super::logs::Entity>,
    #[sea_orm(has_many)]
    pub messages: HasMany<super::messages::Entity>,
    #[sea_orm(has_many)]
    pub slack_threads: HasMany<super::slack_threads::Entity>,
    #[sea_orm(
        belongs_to,
        from = "project_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    pub workspaces: BelongsTo<super::workspaces::Entity>,
    #[sea_orm(
        belongs_to,
        from = "user_id",
        to = "id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    pub users: BelongsTo<Option<super::users::Entity>>,
}

impl ActiveModelBehavior for ActiveModel {}
