//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(10))")]
pub enum UserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "deleted")]
    Deleted,
}

impl UserStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            UserStatus::Active => "active",
            UserStatus::Deleted => "deleted",
        }
    }

    pub fn from_str(s: &str) -> Result<Self, String> {
        match s {
            "active" => Ok(UserStatus::Active),
            "deleted" => Ok(UserStatus::Deleted),
            _ => Err(format!("Invalid status: {s}")),
        }
    }
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub name: String,
    pub picture: Option<String>,
    pub email_verified: bool,
    pub magic_link_token: Option<String>,
    pub magic_link_token_expires_at: Option<DateTimeWithTimeZone>,
    pub status: UserStatus,
    pub created_at: DateTimeWithTimeZone,
    pub last_login_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub api_keys: HasMany<super::api_keys::Entity>,
    #[sea_orm(has_many)]
    pub logs: HasMany<super::logs::Entity>,
    #[sea_orm(has_many)]
    pub org_members: HasMany<super::org_members::Entity>,
    #[sea_orm(has_many)]
    pub secrets: HasMany<super::secrets::Entity>,
    #[sea_orm(has_many)]
    pub threads: HasMany<super::threads::Entity>,
    #[sea_orm(has_many)]
    pub slack_installations: HasMany<super::slack_installations::Entity>,
    #[sea_orm(has_many)]
    pub slack_user_links: HasMany<super::slack_user_links::Entity>,
    #[sea_orm(has_many)]
    pub slack_oauth_states: HasMany<super::slack_oauth_states::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
