//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(10))")]
pub enum UserStatus {
    #[sea_orm(string_value = "active")]
    Active,
    #[sea_orm(string_value = "deleted")]
    Deleted,
}

impl UserStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            UserStatus::Active => "active",
            UserStatus::Deleted => "deleted",
        }
    }

    pub fn from_str(s: &str) -> Result<Self, String> {
        match s {
            "active" => Ok(UserStatus::Active),
            "deleted" => Ok(UserStatus::Deleted),
            _ => Err(format!("Invalid status: {s}")),
        }
    }
}

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    /// NULL for a frontline worker with no mailbox. The UNIQUE stays: Postgres
    /// permits many NULLs in a unique index, so "at most one user per address"
    /// holds without a partial index or a sentinel.
    ///
    /// Resolving a human BY email is still correct everywhere it happens today
    /// — OAuth collapse, Slack matching, invitations, platform grants — because
    /// a NULL simply never matches, and a frontline worker should not be
    /// reachable through any of those. See `internal-docs/frontline-identity.md`.
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub name: String,
    pub picture: Option<String>,
    pub email_verified: bool,
    pub magic_link_token: Option<String>,
    pub magic_link_token_expires_at: Option<DateTimeWithTimeZone>,
    pub status: UserStatus,
    pub created_at: DateTimeWithTimeZone,
    pub last_login_at: DateTimeWithTimeZone,
    #[sea_orm(has_many)]
    pub api_keys: HasMany<super::api_keys::Entity>,
    #[sea_orm(has_many)]
    pub logs: HasMany<super::logs::Entity>,
    #[sea_orm(has_many)]
    pub org_members: HasMany<super::org_members::Entity>,
    #[sea_orm(has_many)]
    pub secrets: HasMany<super::secrets::Entity>,
    #[sea_orm(has_many)]
    pub threads: HasMany<super::threads::Entity>,
    #[sea_orm(has_many)]
    pub slack_installations: HasMany<super::slack_installations::Entity>,
    #[sea_orm(has_many)]
    pub slack_user_links: HasMany<super::slack_user_links::Entity>,
    #[sea_orm(has_many)]
    pub slack_oauth_states: HasMany<super::slack_oauth_states::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    /// A human-readable label for logs, audit entries and display.
    ///
    /// The address when there is one, otherwise `name` — which is NOT NULL and
    /// is what `get_or_create_user` populates (falling back to the email when a
    /// provider gives no name). This is why frontline identity needed no new
    /// `handle` column: the non-null human-readable identifier already existed.
    ///
    /// Never resolve a user by this. It is not unique.
    pub fn label(&self) -> &str {
        self.email.as_deref().unwrap_or(&self.name)
    }
}
