//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.11

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(20))")]
pub enum WorkspaceProvider {
    #[sea_orm(string_value = "github")]
    Github,
    #[sea_orm(string_value = "gitlab")]
    Gitlab,
    #[sea_orm(string_value = "bitbucket")]
    Bitbucket,
}

impl WorkspaceProvider {
    pub fn as_str(&self) -> &'static str {
        match self {
            WorkspaceProvider::Github => "github",
            WorkspaceProvider::Gitlab => "gitlab",
            WorkspaceProvider::Bitbucket => "bitbucket",
        }
    }

    pub fn from_str(s: &str) -> Result<Self, String> {
        match s {
            "github" => Ok(WorkspaceProvider::Github),
            "gitlab" => Ok(WorkspaceProvider::Gitlab),
            "bitbucket" => Ok(WorkspaceProvider::Bitbucket),
            _ => Err(format!("Invalid workspace provider: {s}")),
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::N(20))")]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum WorkspaceStatus {
    #[sea_orm(string_value = "ready")]
    #[default]
    Ready,
    #[sea_orm(string_value = "cloning")]
    Cloning,
    #[sea_orm(string_value = "failed")]
    Failed,
    /// Clone completed, but the repository is missing a `config.yml` at the
    /// workspace root — so it isn't an Oxy project. The user can open the IDE
    /// to add one; retrying the clone won't help.
    #[sea_orm(string_value = "not_oxy_project")]
    NotOxyProject,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "workspaces")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub git_namespace_id: Option<Uuid>,
    pub git_remote_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    /// Filesystem path to the workspace directory (contains config.yml).
    pub path: Option<String>,
    /// Last time this workspace was opened in the UI.
    pub last_opened_at: Option<DateTimeWithTimeZone>,
    /// User who created this workspace. Null for workspaces created before this field was added.
    pub created_by: Option<Uuid>,
    /// Organization this workspace belongs to. Null for workspaces created before multi-tenancy.
    pub org_id: Option<Uuid>,
    pub status: WorkspaceStatus,
    pub error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::git_namespaces::Entity",
        from = "Column::GitNamespaceId",
        to = "super::git_namespaces::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    GitNamespaces,
    #[sea_orm(
        belongs_to = "super::organizations::Entity",
        from = "Column::OrgId",
        to = "super::organizations::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Organizations,
    #[sea_orm(has_many = "super::workspace_members::Entity")]
    WorkspaceMembers,
    #[sea_orm(has_many = "super::slack_user_preferences::Entity")]
    SlackUserPreferences,
    #[sea_orm(has_many = "super::slack_threads::Entity")]
    SlackThreads,
}

impl Related<super::git_namespaces::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GitNamespaces.def()
    }
}

impl Related<super::organizations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Organizations.def()
    }
}

impl Related<super::workspace_members::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkspaceMembers.def()
    }
}

impl Related<super::slack_user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SlackUserPreferences.def()
    }
}

impl Related<super::slack_threads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SlackThreads.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
