// Generated by oxy. Replace the placeholder SQL strings with your real
// queries — the {{ params.X | sqlquote }} syntax interpolates form state
// into the SQL on the client; oxy gates execution by your project
// membership.

import { useState } from "react";
import { useQuery } from "@oxy-hq/sdk";

type EntityRow = { entity: string };
type SummaryRow = { entity: string; total: number; first_seen: string; last_seen: string };
type ActivityRow = { date: string; value: number };

export function App() {
  const [selected, setSelected] = useState<string>("1");

  const entities = useQuery<EntityRow>({
    sql: "-- TODO: replace with your SQL. Example: SELECT CAST(id AS VARCHAR) AS entity FROM table GROUP BY 1 ORDER BY 1",
  });

  const summary = useQuery<SummaryRow>({
    sql: "-- TODO: replace with your SQL. Example: SELECT CAST(id AS VARCHAR) AS entity, COUNT(*) AS total, MIN(date) AS first_seen, MAX(date) AS last_seen FROM table WHERE CAST(id AS VARCHAR) = {{ params.entity | sqlquote }} GROUP BY 1",
  }, { params: { entity: selected } });

  const activity = useQuery<ActivityRow>({
    sql: "-- TODO: replace with your SQL. Example: SELECT date_col AS date, metric AS value FROM table WHERE CAST(id AS VARCHAR) = {{ params.entity | sqlquote }} ORDER BY 1 DESC LIMIT 12",
  }, { params: { entity: selected } });

  return (
    <main className="mx-auto max-w-3xl p-6">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold">{{APP_DISPLAY_NAME}}</h1>
        <p className="text-sm text-gray-600">Single-entity deep-dive — replace the placeholder SQL.</p>
      </header>

      <section className="mb-6">
        <label className="block text-sm font-medium" htmlFor="entity-select">Entity</label>
        <select
          id="entity-select"
          className="mt-1 block w-full rounded-md border px-3 py-2 text-sm"
          value={selected}
          onChange={(e) => setSelected(e.target.value)}
        >
          {entities.rows.map((row) => (
            <option key={row.entity} value={row.entity}>
              {row.entity}
            </option>
          ))}
        </select>
      </section>

      <section className="mb-6 rounded-md border p-4">
        <h2 className="mb-2 text-sm font-medium uppercase text-gray-500">Summary</h2>
        {summary.loading && <p>Loading…</p>}
        {summary.error && <p style={{ color: "red" }}>{summary.error.message}</p>}
        {summary.rows.map((row) => (
          <dl key={row.entity} className="space-y-1 text-sm">
            <div className="flex justify-between"><dt className="text-gray-500">Total</dt><dd>{row.total}</dd></div>
            <div className="flex justify-between"><dt className="text-gray-500">First seen</dt><dd>{row.first_seen}</dd></div>
            <div className="flex justify-between"><dt className="text-gray-500">Last seen</dt><dd>{row.last_seen}</dd></div>
          </dl>
        ))}
      </section>

      <section>
        <h2 className="mb-2 text-sm font-medium uppercase text-gray-500">Recent activity</h2>
        <ul className="divide-y rounded-md border">
          {activity.rows.map((row) => (
            <li key={row.date} className="flex justify-between px-3 py-2 text-sm">
              <span className="font-mono">{row.date}</span>
              <span>{row.value}</span>
            </li>
          ))}
        </ul>
      </section>
    </main>
  );
}
