import { useState } from "react";
import {
  ShieldCheck,
  Sparkles,
  ChevronDown,
  ChevronUp,
  Info,
  Layers,
  Database,
  GitBranch,
  Plug,
  Wrench,
} from "lucide-react";
import { Button } from "@/components/ui/shadcn/button";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@/components/ui/shadcn/collapsible";
import { cn } from "@/libs/shadcn/utils";
import { Card } from "@/components/ui/shadcn/card";

export default function InfoLegend() {
  const [isOpen, setIsOpen] = useState(false);

  const verifiedItems = [
    {
      icon: Layers,
      label: "Semantic Query",
      description: "Pre-defined semantic layer with curated metrics",
      color: "text-blue-600",
    },
    {
      icon: Plug,
      label: "OmniQuery",
      description: "Pre-defined integration query",
      color: "text-cyan-600",
    },
    {
      icon: GitBranch,
      label: "Workflow",
      description: "Workflow defined inline in agent config",
      color: "text-purple-600",
    },
  ];

  const generatedItems = [
    {
      icon: Database,
      label: "LLM SQL",
      description: "SQL generated by LLM from natural language",
      color: "text-orange-600",
    },
    {
      icon: Wrench,
      label: "Agent Tool",
      description: "Agent tool asset with LLM-generated response",
      color: "text-rose-600",
    },
  ];

  return (
    <Card>
      <Collapsible open={isOpen} onOpenChange={setIsOpen}>
        <CollapsibleTrigger asChild>
          <Button
            variant="ghost"
            className="w-full justify-between p-4 h-auto hover:bg-muted/50"
          >
            <div className="flex items-center gap-2">
              <div className="p-1.5 rounded-lg bg-primary/10">
                <Info className="w-4 h-4 text-primary" />
              </div>
              <span className="font-medium">
                Understanding Verified vs Generated Executions
              </span>
            </div>
            {isOpen ? (
              <ChevronUp className="w-4 h-4" />
            ) : (
              <ChevronDown className="w-4 h-4" />
            )}
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="px-4 pb-4 border-t">
            <div className="grid md:grid-cols-2 gap-6 pt-4">
              {/* Verified Column */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <div className="p-1.5 rounded-lg bg-primary/10">
                    <ShieldCheck className="w-4 h-4 text-primary" />
                  </div>
                  <h4 className="font-semibold">Verified</h4>
                  <span className="text-xs text-muted-foreground">
                    (Deterministic)
                  </span>
                </div>
                <p className="text-sm text-muted-foreground mb-3">
                  Pre-defined execution paths that produce consistent,
                  predictable results. These are curated by developers and
                  validated before deployment.
                </p>
                <div className="space-y-2">
                  {verifiedItems.map((item) => (
                    <div
                      key={item.label}
                      className="flex items-start gap-2 p-2 bg-muted/50 rounded-lg"
                    >
                      <item.icon
                        className={cn(
                          "w-4 h-4 mt-0.5 flex-shrink-0 text-primary",
                        )}
                      />
                      <div>
                        <span className="text-sm font-medium">
                          {item.label}
                        </span>
                        <p className="text-xs text-muted-foreground">
                          {item.description}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Generated Column */}
              <div>
                <div className="flex items-center gap-2 mb-3">
                  <div className="p-1.5 rounded-lg bg-primary/10">
                    <Sparkles className="w-4 h-4 text-primary" />
                  </div>
                  <h4 className="font-semibold">Generated</h4>
                  <span className="text-xs text-muted-foreground">
                    (LLM on-the-fly)
                  </span>
                </div>
                <p className="text-sm text-muted-foreground mb-3">
                  Dynamically created by LLM at runtime. Results may vary and
                  require validation. Use for exploratory queries and novel
                  questions.
                </p>
                <div className="space-y-2">
                  {generatedItems.map((item) => (
                    <div
                      key={item.label}
                      className="flex items-start gap-2 p-2 bg-muted/50 rounded-lg"
                    >
                      <item.icon
                        className={cn(
                          "w-4 h-4 mt-0.5 flex-shrink-0 text-primary",
                        )}
                      />
                      <div>
                        <span className="text-sm font-medium">
                          {item.label}
                        </span>
                        <p className="text-xs text-muted-foreground">
                          {item.description}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Key Insight */}
            <div className="mt-4 p-3 bg-primary/5 rounded-lg border border-primary/10">
              <p className="text-sm">
                <strong>Key Insight:</strong> A higher Verified percentage
                indicates more predictable and reliable query execution.
                Consider converting frequently-used Generated queries into
                Verified ones by creating semantic models.
              </p>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </Card>
  );
}
