import {
  ChevronDown,
  ChevronUp,
  Database,
  GitBranch,
  Info,
  Layers,
  Plug,
  ShieldCheck,
  Sparkles,
  Wrench
} from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/shadcn/button";
import { Card } from "@/components/ui/shadcn/card";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger
} from "@/components/ui/shadcn/collapsible";
import { cn } from "@/libs/shadcn/utils";

export default function InfoLegend() {
  const [isOpen, setIsOpen] = useState(false);

  const verifiedItems = [
    {
      icon: Layers,
      label: "Semantic Query",
      description: "Pre-defined semantic layer with curated metrics",
      color: "text-blue-600"
    },
    {
      icon: Plug,
      label: "OmniQuery",
      description: "Pre-defined integration query",
      color: "text-cyan-600"
    },
    {
      icon: GitBranch,
      label: "Workflow",
      description: "Workflow defined inline in agent config",
      color: "text-purple-600"
    }
  ];

  const generatedItems = [
    {
      icon: Database,
      label: "LLM SQL",
      description: "SQL generated by LLM from natural language",
      color: "text-orange-600"
    },
    {
      icon: Wrench,
      label: "Agent Tool",
      description: "Agent tool asset with LLM-generated response",
      color: "text-rose-600"
    }
  ];

  return (
    <Card>
      <Collapsible open={isOpen} onOpenChange={setIsOpen}>
        <CollapsibleTrigger asChild>
          <Button variant='ghost' className='h-auto w-full justify-between p-4 hover:bg-muted/50'>
            <div className='flex items-center gap-2'>
              <div className='rounded-lg bg-primary/10 p-1.5'>
                <Info className='h-4 w-4 text-primary' />
              </div>
              <span className='font-medium'>Understanding Verified vs Generated Executions</span>
            </div>
            {isOpen ? <ChevronUp className='h-4 w-4' /> : <ChevronDown className='h-4 w-4' />}
          </Button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className='border-t px-4 pb-4'>
            <div className='grid gap-6 pt-4 md:grid-cols-2'>
              {/* Verified Column */}
              <div>
                <div className='mb-3 flex items-center gap-2'>
                  <div className='rounded-lg bg-primary/10 p-1.5'>
                    <ShieldCheck className='h-4 w-4 text-primary' />
                  </div>
                  <h4 className='font-semibold'>Verified</h4>
                  <span className='text-muted-foreground text-xs'>(Deterministic)</span>
                </div>
                <p className='mb-3 text-muted-foreground text-sm'>
                  Pre-defined execution paths that produce consistent, predictable results. These
                  are curated by developers and validated before deployment.
                </p>
                <div className='space-y-2'>
                  {verifiedItems.map((item) => (
                    <div
                      key={item.label}
                      className='flex items-start gap-2 rounded-lg bg-muted/50 p-2'
                    >
                      <item.icon className={cn("mt-0.5 h-4 w-4 flex-shrink-0 text-primary")} />
                      <div>
                        <span className='font-medium text-sm'>{item.label}</span>
                        <p className='text-muted-foreground text-xs'>{item.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Generated Column */}
              <div>
                <div className='mb-3 flex items-center gap-2'>
                  <div className='rounded-lg bg-primary/10 p-1.5'>
                    <Sparkles className='h-4 w-4 text-primary' />
                  </div>
                  <h4 className='font-semibold'>Generated</h4>
                  <span className='text-muted-foreground text-xs'>(LLM on-the-fly)</span>
                </div>
                <p className='mb-3 text-muted-foreground text-sm'>
                  Dynamically created by LLM at runtime. Results may vary and require validation.
                  Use for exploratory queries and novel questions.
                </p>
                <div className='space-y-2'>
                  {generatedItems.map((item) => (
                    <div
                      key={item.label}
                      className='flex items-start gap-2 rounded-lg bg-muted/50 p-2'
                    >
                      <item.icon className={cn("mt-0.5 h-4 w-4 flex-shrink-0 text-primary")} />
                      <div>
                        <span className='font-medium text-sm'>{item.label}</span>
                        <p className='text-muted-foreground text-xs'>{item.description}</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            {/* Key Insight */}
            <div className='mt-4 rounded-lg border border-primary/10 bg-primary/5 p-3'>
              <p className='text-sm'>
                <strong>Key Insight:</strong> A higher Verified percentage indicates more
                predictable and reliable query execution. Consider converting frequently-used
                Generated queries into Verified ones by creating semantic models.
              </p>
            </div>
          </div>
        </CollapsibleContent>
      </Collapsible>
    </Card>
  );
}
