//! `oxy init-ci` — generate a **safe** GitHub Actions workflow for trusted
//! publishing (design §8).
//!
//! `id-token: write` is a job-level permission visible to every step, so any
//! third-party action in the job can request an Oxy credential. The generated
//! workflow is therefore **two jobs**: `build` (no id-token) produces an artifact,
//! and `publish` (with id-token, gated on an `environment`) does nothing but
//! download the artifact and publish. Nothing else in the publish job can touch
//! the token.
//!
//! This command only writes a file and prints the publisher registration the
//! operator must complete — it never reads or mutates the repo.

use std::path::Path;
use std::process::Command;

use clap::Parser;
use oxy::theme::StyledText;
use oxy_shared::errors::OxyError;

#[derive(Parser, Debug)]
pub struct InitCiArgs {
    /// The app to publish, "org-slug/app-slug". Printed into the publisher
    /// registration hint and the workflow's publish command.
    #[arg(long)]
    app: Option<String>,
    /// The GitHub Actions environment the publish job runs in. Attach
    /// required-reviewers to it in the repo settings to gate publishes.
    #[arg(long, default_value = "oxy-publish")]
    environment: String,
    /// Overwrite an existing workflow file.
    #[arg(long)]
    force: bool,
}

const WORKFLOW_PATH: &str = ".github/workflows/oxy-publish.yml";

pub async fn handle_init_ci_command(args: InitCiArgs) -> Result<(), OxyError> {
    let (owner, repo) = detect_repo().unwrap_or_else(|| ("<owner>".into(), "<repo>".into()));
    let app = args.app.as_deref().unwrap_or("<org-slug>/<app-slug>");

    let path = Path::new(WORKFLOW_PATH);
    if path.exists() && !args.force {
        return Err(OxyError::ConfigurationError(format!(
            "{WORKFLOW_PATH} already exists — pass --force to overwrite"
        )));
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| OxyError::IOError(format!("create {}: {e}", parent.display())))?;
    }
    std::fs::write(path, workflow_yaml(app, &args.environment))
        .map_err(|e| OxyError::IOError(format!("write {WORKFLOW_PATH}: {e}")))?;

    println!("{} wrote {}", "✓".success(), WORKFLOW_PATH.primary());
    println!();
    println!("{}", "Next: register this workflow as a publisher.".info());
    println!("  An Oxy operator (or you, in the app's settings) registers:");
    println!("    app           {app}");
    println!("    repo_owner    {owner}");
    println!("    repo_owner_id <the numeric GitHub account id of {owner}>");
    println!("    repo_name     {repo}");
    println!("    workflow_ref  {WORKFLOW_PATH}");
    println!("    environment   {}", args.environment);
    println!();
    println!(
        "  The numeric id: {}",
        format!("gh api users/{owner} --jq .id").secondary()
    );
    println!(
        "  Then attach required reviewers to the '{}' environment in\n  Settings → Environments to gate who can publish.",
        args.environment
    );
    Ok(())
}

/// Parse `owner/repo` from `git remote get-url origin`. Best-effort — the workflow
/// is still written with placeholders if there's no git remote.
fn detect_repo() -> Option<(String, String)> {
    let out = Command::new("git")
        .args(["remote", "get-url", "origin"])
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let url = String::from_utf8_lossy(&out.stdout);
    parse_owner_repo(url.trim())
}

/// `git@github.com:owner/repo.git` and `https://github.com/owner/repo(.git)` both
/// reduce to `(owner, repo)`.
fn parse_owner_repo(url: &str) -> Option<(String, String)> {
    let tail = url
        .rsplit_once("github.com")
        .map(|(_, t)| t.trim_start_matches([':', '/']))?;
    let tail = tail.strip_suffix(".git").unwrap_or(tail);
    let (owner, repo) = tail.split_once('/')?;
    if owner.is_empty() || repo.is_empty() {
        return None;
    }
    Some((owner.to_string(), repo.to_string()))
}

fn workflow_yaml(app: &str, environment: &str) -> String {
    format!(
        r#"# Generated by `oxy init-ci`. Trusted publishing — no stored secret.
#
# `id-token: write` is job-level and visible to every step, so the publish job is
# isolated: it does nothing but download the build artifact and publish. Keep it
# that way — do not add other steps or unpinned actions to the publish job.
name: Publish to Oxy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # No id-token here — the build must not be able to mint a publish credential.
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: oxy-bundle
          path: dist

  publish:
    needs: build
    runs-on: ubuntu-latest
    # Required so you can attach required-reviewers in Settings → Environments.
    environment: {environment}
    permissions:
      id-token: write   # the entire secret story — request Oxy's audience below
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: oxy-bundle
          path: dist
      # Pin third-party actions by SHA in a real workflow.
      - uses: oxy-hq/publish-action@v1
        with:
          app: {app}
          dir: dist
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_ssh_and_https_remotes() {
        assert_eq!(
            parse_owner_repo("git@github.com:acme-consulting/northwind-dashboard.git"),
            Some(("acme-consulting".into(), "northwind-dashboard".into()))
        );
        assert_eq!(
            parse_owner_repo("https://github.com/acme-consulting/northwind-dashboard"),
            Some(("acme-consulting".into(), "northwind-dashboard".into()))
        );
        assert_eq!(parse_owner_repo("https://gitlab.com/x/y"), None);
    }

    #[test]
    fn workflow_isolates_the_publish_job() {
        let y = workflow_yaml("acme/dash", "oxy-publish");
        // Compare by JOB SECTION, not by first occurrence: the top comment
        // deliberately mentions `id-token: write` while explaining the isolation,
        // so a naive `find` would match the comment. Slice out each job body.
        let build_start = y.find("  build:").expect("build job present");
        let publish_start = y.find("  publish:").expect("publish job present");
        let build_job = &y[build_start..publish_start];
        let publish_job = &y[publish_start..];

        // The build job must NOT be able to mint a credential. Check the
        // permission LINE, not the bare substring — the build job's own comment
        // says "No id-token here", which contains "id-token" but grants nothing.
        assert!(
            !build_job.contains("id-token: write"),
            "build job must not carry the id-token permission"
        );
        // The publish job carries it, gated on an environment.
        assert!(publish_job.contains("id-token: write"));
        assert!(publish_job.contains("environment: oxy-publish"));
    }
}
