"""Wire-format compatibility tests between the Python device-side
identity module and the Rust backend's `service::fleet`.

The risk this test guards against: the HMAC inputs drift — e.g.
backend changes the separator byte, or one side starts
serializing the timestamp as binary instead of ASCII. Such drift
would silently break every device's announce/bootstrap, so we
pin known-good vectors here.

The vectors below were generated by:
  1. Computing the signature in Python via `_announce_signature`.
  2. Asserting the same value is produced by Rust via
     `expected_announce_signature` in the unit-test layer.

If either side changes the wire format, regenerate via the
`update_vectors.py` helper (left as a TODO when the format
actually stabilizes).
"""
from __future__ import annotations

import base64
import uuid
from pathlib import Path

import pytest

# Ensure the worker package on sys.path. Running pytest from
# `video-poc/edge` resolves it; running from elsewhere uses this
# fallback so contributors don't fight pytest paths.
import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from worker.identity import DeviceIdentity, _announce_signature  # noqa: E402


# ── Fixed test vectors ─────────────────────────────────────────────

# A known UUID + secret + timestamp. The expected signature is the
# SHA-256-HMAC over `device_id.bytes || "." || str(timestamp).encode()`
# keyed on `secret`. The hex value is what the Rust unit tests
# (service::fleet::tests::announce_signature_roundtrip) produce
# for the same inputs.
_KNOWN_DEVICE_ID = uuid.UUID("00000000-0000-7000-8000-000000000000")
_KNOWN_SECRET = bytes(range(32))  # 0x00..0x1f
_KNOWN_TIMESTAMP = 1700000000
# Computed deterministically from the inputs above. If this
# changes, audit the wire format on both sides before updating —
# silently bumping the value defeats the test.
# Cross-verified against the Rust unit test
# `service::fleet::tests::announce_signature_compat_vector`. If you
# need to change this, audit both sides and bump the pin in lockstep.
_EXPECTED_SIG_HEX = (
    "ef4d4b583f463600a4d61945fef776fb0d4eefe6a2335e97052b2ccdb24d1028"
)


def test_announce_signature_matches_pinned_vector():
    """Pin the wire format. If this drifts, every device's
    announce/bootstrap stops working — must be a deliberate change
    on both sides."""
    sig = _announce_signature(_KNOWN_SECRET, _KNOWN_DEVICE_ID, _KNOWN_TIMESTAMP)
    assert sig.hex() == _EXPECTED_SIG_HEX


def test_identity_save_load_roundtrip(tmp_path):
    """The on-disk format round-trips losslessly. Secrets + UUIDs
    preserved exactly."""
    path = tmp_path / "device.json"
    ident = DeviceIdentity.generate(sku="test", hardware_revision="rev-A")
    ident.save(path)
    loaded = DeviceIdentity.load(path)
    assert loaded == ident


def test_identity_save_uses_0600_perms(tmp_path):
    """Anyone with disk access could exfiltrate the secret if the
    perms slip — this is the trust boundary."""
    path = tmp_path / "device.json"
    DeviceIdentity.generate(sku="t", hardware_revision="r").save(path)
    mode = path.stat().st_mode & 0o777
    assert mode == 0o600, f"expected 0o600, got {oct(mode)}"


def test_identity_load_returns_none_when_missing(tmp_path):
    """First boot: file doesn't exist yet → caller generates +
    saves. None signals 'go generate' without raising."""
    assert DeviceIdentity.load(tmp_path / "does_not_exist.json") is None


def test_identity_load_raises_on_corruption(tmp_path):
    """A corrupted file should NOT silently get overwritten — that
    would lose the device_secret and brick the box's identity."""
    path = tmp_path / "device.json"
    path.write_text("{not valid json")
    with pytest.raises(Exception):
        DeviceIdentity.load(path)


def test_announce_signature_b64_round_trips():
    """The convenience method emits unpadded base64 the backend
    expects (STANDARD_NO_PAD on the Rust side via base64 crate)."""
    ident = DeviceIdentity.generate(sku="t", hardware_revision="r")
    ts, b64 = ident.announce_signature_b64(timestamp=1700000000)
    # Reconstruct the raw signature and verify it matches.
    raw = ident.announce_signature(ts)
    decoded = base64.b64decode(b64 + "=" * (-len(b64) % 4))
    assert decoded == raw


def test_announce_signature_depends_on_timestamp():
    """A replayed signature won't pass the server's HMAC check —
    different timestamps must produce different signatures."""
    ident = DeviceIdentity.generate(sku="t", hardware_revision="r")
    a = ident.announce_signature(1700000000)
    b = ident.announce_signature(1700000001)
    assert a != b


def test_announce_signature_depends_on_device_id():
    """Two devices with the same secret + timestamp still produce
    different signatures — protects against accidental
    identity confusion."""
    secret = bytes(32)
    a = _announce_signature(
        secret, uuid.UUID("00000000-0000-7000-8000-000000000001"), 1700000000
    )
    b = _announce_signature(
        secret, uuid.UUID("00000000-0000-7000-8000-000000000002"), 1700000000
    )
    assert a != b


def test_uuid7_version():
    """We rely on v7 for sortable creation-time. v4 would break
    correlation of registry rows with shipment timing."""
    ident = DeviceIdentity.generate(sku="t", hardware_revision="r")
    assert ident.device_id.version == 7
