[package]
name = "onyx-desktop"
version = "0.1.0"
description = "Onyx"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "onyx_desktop"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.1", features = ["config-json5"] }

[dependencies]
onyx = { path = "../../" }

serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.0.3", features = ["config-json5"] }
tauri-plugin-log = "2.0.0-rc"
tokio = { version = "1.41", features = ["full"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
