use sea_orm::entity::prelude::*;

/// Factory-burned identity. One row per physical device ever made.
///
/// `device_id` is supplied by the factory enrollment call (the
/// device generates a UUID v7 at first boot and presents it to
/// `POST /fleet/factory-enroll`), not auto-generated by the DB —
/// keeps the identity stable across re-enrollment of a returned
/// device.
///
/// `device_secret` is the 32-byte shared secret used for HMAC-SHA256
/// signing of `/fleet/announce`. Stored raw here because HMAC
/// verification needs the key — V1 accepts that DB compromise
/// leaks every device's secret (which is the same compromise
/// level as plain workspace data). A future phase should add
/// field-level encryption with a deployment KEK before any
/// production deploy outside the POC.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "device_registry")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub device_id: Uuid,
    pub sku: String,
    pub hardware_revision: String,
    pub manufactured_at: DateTimeWithTimeZone,
    pub device_secret: Vec<u8>,
    /// Sticky — derived from `(device_id || global_claim_salt)` so
    /// re-printing a label or re-enrolling a returned device
    /// produces the same code. Operators read this off the case /
    /// QR sticker when scanning to claim.
    pub claim_code: String,
    /// Updated by `POST /fleet/announce` on every successful
    /// signature verification. Drives "device offline" detection
    /// in a future fleet observability tab.
    pub last_announce_at: Option<DateTimeWithTimeZone>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::device_claims::Entity")]
    Claim,
}

impl Related<super::device_claims::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Claim.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
