/** Tooltip for queries compiled by the airlayer semantic layer. */
export const VERIFIED_TOOLTIP = "Verified — generated by the semantic layer";

/** Tooltip for queries sourced from a pre-written SQL file in the agent context. */
export const VERIFIED_SQL_FILE_TOOLTIP = "Verified — pre-written query";
