from onyx.catalog.features.agent import (
    agent_created,
    agent_deleted,
    agent_published,
    create_agent,
    create_dev_agent,
    delete_agent,
    discard_agent_changes,
    get_agent,
    get_agent_by_subdomain,
    get_agent_id_by_published_subdomain,
    get_agent_info,
    get_agent_version_by_name,
    get_dev_agent,
    get_published_agent,
    get_published_agent_by_subdomain,
    get_published_agent_version_by_agent_ids,
    is_name_available,
    is_subdomain_available,
    list_agent_categories,
    list_agents,
    list_dev_agents,
    list_published_agents,
    list_published_agents_by_category,
    list_recent_agents,
    list_subdomains,
    public_agent,
    publish_agent,
    search_agents,
    search_agents_by_keyword,
    search_suggestions,
    search_view,
    update_agent_info,
    update_agent_knowledge,
)
from onyx.catalog.features.agent.queries import get_random_published_agents
from onyx.catalog.features.cms import (
    featured_agents,
    import_agent_categories,
    list_agents_by_organization,
    list_agents_by_tab,
    list_discover_tabs,
    lookup_agent_subdomain,
    publish_discover_tabs,
)
from onyx.catalog.features.data_sources import (
    create_integration,
    delete_integration,
    get_connection_by_name,
    get_gmail_refresh_token,
    get_gmail_user_info,
    get_integration_by_name,
    get_notion_access_token,
    get_notion_user_info,
    get_salesforce_refresh_token,
    get_salesforce_user_info,
    get_slack_oauth_access,
    integration_created,
    list_data_sources,
    sync_connection,
    sync_integration,
)
from onyx.catalog.features.data_sources.commands import (
    connection_created,
    create_connection,
    run_query,
    test_connection,
    update_connection,
)
from onyx.catalog.features.ingest import (
    ingest_connection,
    ingest_integration,
    update_connection_sync_state,
    update_integration_sync_state,
)
from onyx.catalog.features.prompts import add_prompt, delete_prompt, list_agent_prompts, update_prompt
from onyx.catalog.features.search import searched
from onyx.catalog.features.stats import (
    count_like_by_agent,
    create_user_agent_like,
    delete_user_agent_like,
    get_user_agent_like,
)
from onyx.catalog.models.all import *  # noqa initilize all models before engine & session
from onyx.shared.services.base import Service

catalog_service = Service("catalog")
catalog_service.with_handlers(
    # data_sources
    create_integration,
    delete_integration,
    get_connection_by_name,
    get_gmail_refresh_token,
    get_gmail_user_info,
    get_integration_by_name,
    get_notion_access_token,
    get_notion_user_info,
    get_salesforce_refresh_token,
    get_salesforce_user_info,
    get_slack_oauth_access,
    integration_created,
    list_data_sources,
    sync_connection,
    sync_integration,
    create_connection,
    update_connection,
    connection_created,
    run_query,
    test_connection,
    # ingest
    ingest_connection,
    ingest_integration,
    update_connection_sync_state,
    update_integration_sync_state,
    # agent
    list_agent_categories,
    list_published_agents_by_category,
    search_agents,
    search_view,
    search_suggestions,
    create_dev_agent,
    create_agent,
    delete_agent,
    agent_deleted,
    discard_agent_changes,
    get_dev_agent,
    get_agent_by_subdomain,
    get_agent_id_by_published_subdomain,
    get_agent_version_by_name,
    get_agent,
    get_published_agent_by_subdomain,
    get_published_agent_version_by_agent_ids,
    get_published_agent,
    is_name_available,
    is_subdomain_available,
    list_dev_agents,
    list_agents,
    list_recent_agents,
    list_published_agents,
    agent_created,
    public_agent,
    publish_agent,
    import_agent_categories,
    publish_discover_tabs,
    list_discover_tabs,
    list_agents_by_tab,
    list_agents_by_organization,
    lookup_agent_subdomain,
    agent_published,
    update_agent_info,
    update_agent_knowledge,
    get_agent_info,
    featured_agents,
    list_subdomains,
    # stats
    count_like_by_agent,
    create_user_agent_like,
    delete_user_agent_like,
    get_user_agent_like,
    # prompts
    add_prompt,
    delete_prompt,
    list_agent_prompts,
    update_prompt,
    searched,
    search_agents_by_keyword,
    get_random_published_agents,
)
