# yaml-language-server: $schema=../json-schemas/workflow.json

name: table_values_sample
steps:
  - name: intervals
    type: execute_sql
    warehouse: primary_warehouse
    sql_file: example_intervals.sql
  - name: schedules
    type: loop_sequential
    values: "{{intervals.intervals}}"
    steps:
      - name: report
        type: formatter
        template: |
          ---
          Schedule by Interval: {{schedules.value}}
          ---

  - name: formatter
    type: formatter
    template: |
      # Debugging
      Row-based display:
      {{intervals}}
      Column-based display:
      {{intervals.intervals}}
      Values in loop:
      {% for schedule in schedules %}
      {{schedule.report}}
      {% endfor %}
