# yaml-language-server: $schema=https://raw.githubusercontent.com/onyx-hq/onyx-public-releases/refs/heads/main/json-schemas/config.json

databases:
  - name: primary_database
    type: bigquery
    key_path: bigquery-sample.key
    dataset: dbt_prod_core

  - name: local
    type: duckdb
    key_path: None
    dataset: .db/

models:
  - name: openai-4o-mini
    vendor: openai
    model_ref: gpt-4o-mini
    key_var: OPENAI_API_KEY
  - name: openai-4o
    vendor: openai
    model_ref: gpt-4o
    key_var: OPENAI_API_KEY
  # - name: openai-4o-mini-azure
  #   vendor: openai
  #   model_ref: openai-4o-mini-azure
  #   api_url:  https://dsmsmachatgpt4opoc.openai.azure.com
  #   azure_deployment_id: "SMART-Automated-gpt-4o"
  #   azure_api_version: "2024-08-01-preview"
  #   key_var: OPENAI_AZURE_KEY
  - name: llama3.2
    vendor: ollama
    model_ref: llama3.2:latest
    api_url: http://localhost:11434/v1
    api_key: secret

retrievals:
  - name: default
    embed_model: "bge-small-en-v1.5"
    rerank_model: "jina-reranker-v2-base-multiligual"
    top_k: 10
    factor: 5