// Generated by oxy. Replace the placeholder SQL strings with your real
// queries — the {{ params.X | sqlquote }} syntax interpolates form state
// into the SQL on the client; oxy gates execution by your project
// membership.

import { useState } from "react";
import { useQuery } from "@oxy-hq/sdk";
import {
  CartesianGrid,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

type EntityRow = { entity: string; count: number };
type KpiRow = { label: string; value: number };
type TimeSeriesRow = { date: string; value: number };

export function App() {
  const [selected, setSelected] = useState<string>("all");

  const entities = useQuery<EntityRow>({
    sql: "-- TODO: replace with your SQL. Example: SELECT col AS entity, COUNT(*) AS count FROM table GROUP BY 1 ORDER BY 2 DESC LIMIT 10",
  });

  const kpis = useQuery<KpiRow>({
    sql: "-- TODO: replace with your SQL. Example: SELECT 'total' AS label, COUNT(*) AS value FROM table WHERE {{ params.entity | default('1=1') }}",
  }, { params: { entity: selected } });

  const trend = useQuery<TimeSeriesRow>({
    sql: "-- TODO: replace with your SQL. Example: SELECT date_col AS date, SUM(metric) AS value FROM table GROUP BY 1 ORDER BY 1",
  });

  return (
    <main className="mx-auto max-w-6xl p-6">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold">{{APP_DISPLAY_NAME}}</h1>
        <p className="text-sm text-gray-600">Multi-metric dashboard — replace the placeholder SQL.</p>
      </header>

      <section className="mb-6 grid grid-cols-1 gap-3 sm:grid-cols-3">
        {kpis.loading && <p>Loading KPIs…</p>}
        {kpis.error && <p style={{ color: "red" }}>{kpis.error.message}</p>}
        {kpis.rows.map((kpi) => (
          <div key={kpi.label} className="rounded-md border p-4">
            <div className="text-xs uppercase text-gray-500">{kpi.label}</div>
            <div className="mt-1 text-2xl font-semibold">{kpi.value}</div>
          </div>
        ))}
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-sm font-medium uppercase text-gray-500">Trend</h2>
        <div className="h-64 rounded-md border p-2">
          {trend.loading ? (
            <p>Loading trend…</p>
          ) : trend.error ? (
            <p style={{ color: "red" }}>{trend.error.message}</p>
          ) : (
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={trend.rows}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="date" />
                <YAxis />
                <Tooltip />
                <Line type="monotone" dataKey="value" stroke="#3b82f6" strokeWidth={2} />
              </LineChart>
            </ResponsiveContainer>
          )}
        </div>
      </section>

      <section>
        <h2 className="mb-2 text-sm font-medium uppercase text-gray-500">Leaderboard</h2>
        <div className="overflow-hidden rounded-md border">
          <table className="w-full text-sm">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-3 py-2 text-left">Entity</th>
                <th className="px-3 py-2 text-right">Count</th>
              </tr>
            </thead>
            <tbody>
              {entities.rows.map((row) => (
                <tr
                  key={row.entity}
                  className="cursor-pointer border-t hover:bg-gray-50"
                  onClick={() => setSelected(row.entity)}
                >
                  <td className="px-3 py-2 font-mono">{row.entity}</td>
                  <td className="px-3 py-2 text-right">{row.count}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>
    </main>
  );
}
