export const monacoGitHubDarkDefaultTheme = {
  base: "vs-dark" as const,
  inherit: true,
  rules: [
    { token: "comment", foreground: "8b949e" },
    { token: "punctuation.definition.comment", foreground: "8b949e" },
    { token: "string.comment", foreground: "8b949e" },

    { token: "constant.other.placeholder", foreground: "ff7b72" },
    { token: "constant.character", foreground: "ff7b72" },
    { token: "constant", foreground: "79c0ff" },
    { token: "entity.name.constant", foreground: "79c0ff" },
    { token: "variable.other.constant", foreground: "79c0ff" },
    { token: "variable.language", foreground: "79c0ff" },
    { token: "entity", foreground: "79c0ff" },

    { token: "entity.name", foreground: "ffa657" },
    { token: "meta.export.default", foreground: "ffa657" },
    { token: "meta.definition.variable", foreground: "ffa657" },

    { token: "variable.parameter", foreground: "e6edf3" },
    { token: "meta.jsx.children", foreground: "e6edf3" },
    { token: "meta.block", foreground: "e6edf3" },
    { token: "meta.tag.attributes", foreground: "e6edf3" },
    { token: "meta.object.member", foreground: "e6edf3" },
    { token: "meta.embedded.expression", foreground: "e6edf3" },

    { token: "entity.name.function", foreground: "d2a8ff" },
    { token: "entity.name.tag", foreground: "7ee787" },
    { token: "support.class.component", foreground: "7ee787" },

    { token: "keyword", foreground: "ff7b72" },
    { token: "storage", foreground: "ff7b72" },
    { token: "storage.type", foreground: "ff7b72" },

    { token: "storage.modifier.package", foreground: "e6edf3" },
    { token: "storage.modifier.import", foreground: "e6edf3" },
    { token: "storage.type.java", foreground: "e6edf3" },

    { token: "string", foreground: "a5d6ff" },
    { token: "punctuation.definition.string", foreground: "a5d6ff" },
    { token: "string.quoted", foreground: "a5d6ff" },
    { token: "string.template", foreground: "a5d6ff" },

    { token: "support", foreground: "79c0ff" },
    { token: "support.type", foreground: "79c0ff" },
    { token: "support.function", foreground: "79c0ff" },
    { token: "support.constant", foreground: "79c0ff" },
    { token: "support.variable", foreground: "79c0ff" },

    { token: "meta.property-name", foreground: "79c0ff" },

    { token: "variable", foreground: "ffa657" },
    { token: "variable.other", foreground: "e6edf3" },

    { token: "invalid", foreground: "ffa198", fontStyle: "italic" },
    {
      token: "invalid.deprecated",
      foreground: "ffa198",
      fontStyle: "italic",
    },
    { token: "invalid.illegal", foreground: "ffa198", fontStyle: "italic" },

    { token: "regexp", foreground: "a5d6ff" },
    { token: "string.regexp", foreground: "a5d6ff" },
    { token: "constant.regexp", foreground: "a5d6ff" },
    { token: "string.regexp.character-class", foreground: "a5d6ff" },
    { token: "string.regexp.arbitrary-repetition", foreground: "a5d6ff" },
    {
      token: "string.regexp constant.character.escape",
      foreground: "7ee787",
      fontStyle: "bold",
    },

    { token: "support.type.property-name.json", foreground: "7ee787" },

    { token: "meta.module-reference", foreground: "79c0ff" },
    { token: "keyword.control.import", foreground: "ff7b72" },
    { token: "keyword.control.export", foreground: "ff7b72" },
    { token: "keyword.control.from", foreground: "ff7b72" },

    { token: "markup.list", foreground: "ffa657" },
    { token: "markup.heading", foreground: "79c0ff", fontStyle: "bold" },
    { token: "markup.quote", foreground: "7ee787" },
    { token: "markup.italic", foreground: "e6edf3", fontStyle: "italic" },
    { token: "markup.bold", foreground: "e6edf3", fontStyle: "bold" },
    { token: "markup.underline", fontStyle: "underline" },
    { token: "markup.strikethrough", fontStyle: "strikethrough" },
    { token: "markup.inline.raw", foreground: "79c0ff" },
    { token: "markup.code", foreground: "79c0ff" },
    { token: "markup.link", foreground: "a5d6ff" },

    {
      token: "punctuation.definition.list.begin.markdown",
      foreground: "ffa657",
    },
    { token: "punctuation.definition.embedded", foreground: "ff7b72" },

    { token: "constant.other.reference.link", foreground: "a5d6ff" },
    { token: "string.other.link", foreground: "a5d6ff" },

    { token: "number", foreground: "79c0ff" },

    { token: "entity.name.type", foreground: "ffa657" },
    { token: "entity.other.inherited-class", foreground: "ffa657" },
    { token: "support.class", foreground: "ffa657" },
    { token: "type.identifier", foreground: "ffa657" },

    { token: "keyword.operator", foreground: "e6edf3" },

    { token: "delimiter", foreground: "e6edf3" },
    { token: "delimiter.bracket", foreground: "e6edf3" },
    { token: "delimiter.square", foreground: "e6edf3" },
    { token: "delimiter.curly", foreground: "e6edf3" },
    { token: "delimiter.parenthesis", foreground: "e6edf3" },
    { token: "type", foreground: "7EE787" },
  ],
  colors: {
    focusBorder: "#1f6feb",
    foreground: "#e6edf3",
    descriptionForeground: "#7d8590",
    errorForeground: "#f85149",
    "textLink.foreground": "#2f81f7",
    "textLink.activeForeground": "#2f81f7",
    "textBlockQuote.background": "#010409",
    "textBlockQuote.border": "#30363d",
    "textCodeBlock.background": "#6e768166",
    "textPreformat.foreground": "#7d8590",
    "textPreformat.background": "#6e768166",
    "textSeparator.foreground": "#21262d",
    "icon.foreground": "#7d8590",
    "keybindingLabel.foreground": "#e6edf3",
    "button.background": "#238636",
    "button.foreground": "#ffffff",
    "button.hoverBackground": "#2ea043",
    "button.secondaryBackground": "#282e33",
    "button.secondaryForeground": "#c9d1d9",
    "button.secondaryHoverBackground": "#30363d",
    "checkbox.background": "#161b22",
    "checkbox.border": "#30363d",
    "dropdown.background": "#161b22",
    "dropdown.border": "#30363d",
    "dropdown.foreground": "#e6edf3",
    "dropdown.listBackground": "#161b22",
    "input.background": "#0d1117",
    "input.border": "#30363d",
    "input.foreground": "#e6edf3",
    "input.placeholderForeground": "#6e7681",
    "badge.foreground": "#ffffff",
    "badge.background": "#1f6feb",
    "progressBar.background": "#1f6feb",
    "titleBar.activeForeground": "#7d8590",
    "titleBar.activeBackground": "#0d1117",
    "titleBar.inactiveForeground": "#7d8590",
    "titleBar.inactiveBackground": "#010409",
    "titleBar.border": "#30363d",
    "activityBar.foreground": "#e6edf3",
    "activityBar.inactiveForeground": "#7d8590",
    "activityBar.background": "#0d1117",
    "activityBarBadge.foreground": "#ffffff",
    "activityBarBadge.background": "#1f6feb",
    "activityBar.activeBorder": "#f78166",
    "activityBar.border": "#30363d",
    "sideBar.foreground": "#e6edf3",
    "sideBar.background": "#010409",
    "sideBar.border": "#30363d",
    "sideBarTitle.foreground": "#e6edf3",
    "sideBarSectionHeader.foreground": "#e6edf3",
    "sideBarSectionHeader.background": "#010409",
    "sideBarSectionHeader.border": "#30363d",
    "list.hoverForeground": "#e6edf3",
    "list.inactiveSelectionForeground": "#e6edf3",
    "list.activeSelectionForeground": "#e6edf3",
    "list.hoverBackground": "#6e76811a",
    "list.inactiveSelectionBackground": "#6e768166",
    "list.activeSelectionBackground": "#6e768166",
    "list.focusForeground": "#e6edf3",
    "list.focusBackground": "#388bfd26",
    "list.inactiveFocusBackground": "#388bfd26",
    "list.highlightForeground": "#2f81f7",
    "tree.indentGuidesStroke": "#21262d",
    "notificationCenterHeader.foreground": "#7d8590",
    "notificationCenterHeader.background": "#161b22",
    "notifications.foreground": "#e6edf3",
    "notifications.background": "#161b22",
    "notifications.border": "#30363d",
    "notificationsErrorIcon.foreground": "#f85149",
    "notificationsWarningIcon.foreground": "#d29922",
    "notificationsInfoIcon.foreground": "#2f81f7",
    "pickerGroup.border": "#30363d",
    "pickerGroup.foreground": "#7d8590",
    "quickInput.background": "#161b22",
    "quickInput.foreground": "#e6edf3",
    "statusBar.foreground": "#7d8590",
    "statusBar.background": "#0d1117",
    "statusBar.border": "#30363d",
    "statusBar.focusBorder": "#1f6feb80",
    "statusBar.noFolderBackground": "#0d1117",
    "statusBar.debuggingForeground": "#ffffff",
    "statusBar.debuggingBackground": "#da3633",
    "statusBarItem.prominentBackground": "#6e768166",
    "statusBarItem.remoteForeground": "#e6edf3",
    "statusBarItem.remoteBackground": "#30363d",
    "statusBarItem.hoverBackground": "#e6edf314",
    "statusBarItem.activeBackground": "#e6edf31f",
    "statusBarItem.focusBorder": "#1f6feb",
    "editorGroupHeader.tabsBackground": "#010409",
    "editorGroupHeader.tabsBorder": "#30363d",
    "editorGroup.border": "#30363d",
    "tab.activeForeground": "#e6edf3",
    "tab.inactiveForeground": "#7d8590",
    "tab.inactiveBackground": "#010409",
    "tab.activeBackground": "#0d1117",
    "tab.hoverBackground": "#0d1117",
    "tab.unfocusedHoverBackground": "#6e76811a",
    "tab.border": "#30363d",
    "tab.unfocusedActiveBorderTop": "#30363d",
    "tab.activeBorder": "#0d1117",
    "tab.unfocusedActiveBorder": "#0d1117",
    "tab.activeBorderTop": "#f78166",
    "breadcrumb.foreground": "#7d8590",
    "breadcrumb.focusForeground": "#e6edf3",
    "breadcrumb.activeSelectionForeground": "#7d8590",
    "breadcrumbPicker.background": "#161b22",
    "editor.foreground": "#e6edf3",
    "editor.background": "#0d1117",
    "editorWidget.background": "#161b22",
    "editor.foldBackground": "#6e76811a",
    "editor.lineHighlightBackground": "#6e76811a",
    "editorLineNumber.foreground": "#6e7681",
    "editorLineNumber.activeForeground": "#e6edf3",
    "editorIndentGuide.background": "#e6edf31f",
    "editorIndentGuide.activeBackground": "#e6edf33d",
    "editorWhitespace.foreground": "#484f58",
    "editorCursor.foreground": "#2f81f7",
    "editor.findMatchBackground": "#9e6a03",
    "editor.findMatchHighlightBackground": "#f2cc6080",
    "editor.linkedEditingBackground": "#2f81f712",
    "editor.selectionBackground": "#264f78",
    "editor.selectionHighlightBackground": "#3fb95040",
    "editor.wordHighlightBackground": "#6e768180",
    "editor.wordHighlightStrongBackground": "#6e76814d",
    "editor.wordHighlightBorder": "#6e768199",
    "editor.wordHighlightStrongBorder": "#6e768199",
    "editorBracketMatch.background": "#3fb95040",
    "editorBracketMatch.border": "#3fb95099",
    "editorInlayHint.background": "#8b949e33",
    "editorInlayHint.foreground": "#7d8590",
    "editorInlayHint.typeBackground": "#8b949e33",
    "editorInlayHint.typeForeground": "#7d8590",
    "editorInlayHint.parameterBackground": "#8b949e33",
    "editorInlayHint.parameterForeground": "#7d8590",
    "editorGutter.modifiedBackground": "#bb800966",
    "editorGutter.addedBackground": "#2ea04366",
    "editorGutter.deletedBackground": "#f8514966",
    "diffEditor.insertedTextBackground": "#3fb9504d",
    "diffEditor.removedTextBackground": "#ff7b724d",
    "diffEditor.insertedLineBackground": "#23863626",
    "diffEditor.removedLineBackground": "#da363326",
    "scrollbar.shadow": "#484f5833",
    "scrollbarSlider.background": "#8b949e33",
    "scrollbarSlider.hoverBackground": "#8b949e3d",
    "scrollbarSlider.activeBackground": "#8b949e47",
    "editorOverviewRuler.border": "#010409",

    "editorOverviewRuler.addedForeground": "#2ea04399",
    "editorOverviewRuler.deletedForeground": "#f8514999",
    "editorOverviewRuler.modifiedForeground": "#bb800999",
    "editorOverviewRuler.errorForeground": "#f85149",
    "editorOverviewRuler.warningForeground": "#d29922",
    "editorOverviewRuler.infoForeground": "#2f81f7",

    "minimapSlider.background": "#8b949e33",
    "minimapSlider.hoverBackground": "#8b949e3d",
    "minimapSlider.activeBackground": "#8b949e47",

    "minimapGutter.addedBackground": "#2ea043cc",
    "minimapGutter.deletedBackground": "#f85149cc",
    "minimapGutter.modifiedBackground": "#bb8009cc",
    "panel.background": "#010409",
    "panel.border": "#30363d",
    "panelTitle.activeBorder": "#f78166",
    "panelTitle.activeForeground": "#e6edf3",
    "panelTitle.inactiveForeground": "#7d8590",
    "panelInput.border": "#30363d",
    "debugIcon.breakpointForeground": "#f85149",
    "debugConsole.infoForeground": "#8b949e",
    "debugConsole.warningForeground": "#d29922",
    "debugConsole.errorForeground": "#ffa198",
    "debugConsole.sourceForeground": "#e3b341",
    "debugConsoleInputIcon.foreground": "#bc8cff",

    "debugToolBar.background": "#161b22",
    "editor.stackFrameHighlightBackground": "#bb800966",
    "editor.focusedStackFrameHighlightBackground": "#2ea04366",
    "peekViewEditor.matchHighlightBackground": "#bb800966",
    "peekViewResult.matchHighlightBackground": "#bb800966",
    "peekViewEditor.background": "#6e76811a",
    "peekViewResult.background": "#0d1117",
    "peekViewTitle.background": "#161b22",
    "peekViewTitleLabel.foreground": "#e6edf3",
    "peekViewTitleDescription.foreground": "#7d8590",
    "peekView.border": "#30363d",
    "settings.headerForeground": "#e6edf3",
    "settings.modifiedItemIndicator": "#bb800966",
    "welcomePage.buttonBackground": "#21262d",
    "welcomePage.buttonHoverBackground": "#30363d",

    "terminal.foreground": "#e6edf3",
    "terminal.ansiBlack": "#484f58",
    "terminal.ansiRed": "#ff7b72",
    "terminal.ansiGreen": "#3fb950",
    "terminal.ansiYellow": "#d29922",
    "terminal.ansiBlue": "#58a6ff",
    "terminal.ansiMagenta": "#bc8cff",
    "terminal.ansiCyan": "#39c5cf",
    "terminal.ansiWhite": "#b1bac4",
    "terminal.ansiBrightBlack": "#6e7681",
    "terminal.ansiBrightRed": "#ffa198",
    "terminal.ansiBrightGreen": "#56d364",
    "terminal.ansiBrightYellow": "#e3b341",
    "terminal.ansiBrightBlue": "#79c0ff",
    "terminal.ansiBrightMagenta": "#d2a8ff",
    "terminal.ansiBrightCyan": "#56d4dd",
    "terminal.ansiBrightWhite": "#ffffff",

    "gitDecoration.addedResourceForeground": "#3fb950",
    "gitDecoration.modifiedResourceForeground": "#d29922",
    "gitDecoration.deletedResourceForeground": "#f85149",
    "gitDecoration.untrackedResourceForeground": "#3fb950",
    "gitDecoration.ignoredResourceForeground": "#6e7681",
    "gitDecoration.conflictingResourceForeground": "#db6d28",
    "gitDecoration.submoduleResourceForeground": "#7d8590",

    "editorBracketHighlight.foreground1": "#79c0ff",
    "editorBracketHighlight.foreground2": "#56d364",
    "editorBracketHighlight.foreground3": "#e3b341",
    "editorBracketHighlight.foreground4": "#ffa198",
    "editorBracketHighlight.foreground5": "#ff9bce",
    "editorBracketHighlight.foreground6": "#d2a8ff",
    "editorBracketHighlight.unexpectedBracket.foreground": "#7d8590",
  },
};
