use chrono::{DateTime, Utc};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

use crate::execute::types::{ReferenceKind, Usage};

/// Log types for workflow execution
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema, JsonSchema)]
pub enum LogType {
    #[serde(rename = "success")]
    Success,
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,
}

/// A log item from workflow execution
#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct LogItem {
    pub content: String,
    pub timestamp: DateTime<Utc>,
    pub log_type: LogType,
    pub append: bool,
}

impl LogItem {
    pub fn new(content: String, log_type: LogType) -> Self {
        Self {
            content,
            timestamp: Utc::now(),
            log_type,
            append: false,
        }
    }

    pub fn info(content: String) -> Self {
        Self::new(content, LogType::Info)
    }

    pub fn append(content: String) -> Self {
        let mut log_item = Self::new(content, LogType::Info);
        log_item.append = true;
        log_item
    }

    pub fn error(content: String) -> Self {
        Self::new(content, LogType::Error)
    }
}

/// Information about an artifact generated by an agent
#[derive(Serialize, Deserialize, ToSchema, JsonSchema, Debug, Clone)]
pub struct ArtifactInfo {
    pub id: String,
    pub title: String,
    pub kind: String,
    pub is_verified: bool,
    pub error: Option<String>,
}

/// Response from asking an agent a question
#[derive(Serialize, Deserialize, ToSchema, Debug, Clone)]
pub struct AskAgentResponse {
    pub content: String,
    pub references: Vec<ReferenceKind>,
    pub usage: Option<Usage>,
    pub artifacts: Vec<ArtifactInfo>,
    pub success: bool,
    pub error_message: Option<String>,
}
