config-version: 2

name: "jaffle_shop"
version: "1.0.0"

profile: "jaffle_shop"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

target-path: "target"
clean-targets:
  - "target"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table
