#!/usr/bin/env node
/**
 * Inline the three shipped asset directories into a TypeScript module, so a
 * compiled single-file `oxyc` still has them.
 *
 * `template/`, `skills/` and `json-schemas/` are normally read off disk next to
 * `package.json` (see `src/template/locate.ts`). That works for an npm install
 * and for a source checkout, and not at all for `bun build --compile`, whose
 * output is one executable with no package around it. So the bytes come along
 * inside the bundle and are unpacked on first run.
 *
 * The payload is one gzipped JSON blob rather than a file-per-constant: ~427 KB
 * of mostly-text compresses to a fraction of that, and base64-of-gzip beats
 * base64-of-raw by enough to matter in a file every build parses.
 *
 * Executable bits are carried explicitly. `template/scripts/dev.sh` and the
 * three `.github/scripts/*.sh` are executable in the repo, and a scaffolded
 * workspace whose `dev.sh` is 0644 is broken in a way that looks like a bug in
 * the customer's repo rather than in this generator.
 */

import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";

const pkgRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

/** The directories that ship inside the package, in `files` order. */
const ASSET_DIRS = ["json-schemas", "skills", "template"];

const OUT = join(pkgRoot, "src", "generated", "embedded-assets.ts");

/** Every file under `dir`, relative to the package root, sorted for determinism. */
function walk(dir) {
  const out = [];
  const visit = (abs) => {
    for (const entry of readdirSync(abs, { withFileTypes: true }).sort((a, b) =>
      a.name < b.name ? -1 : a.name > b.name ? 1 : 0
    )) {
      const child = join(abs, entry.name);
      if (entry.isDirectory()) visit(child);
      else if (entry.isFile()) out.push(child);
      // Symlinks are skipped deliberately: none exist today, and silently
      // materialising one as a regular file would be a surprise.
    }
  };
  visit(dir);
  return out;
}

const files = {};
let rawBytes = 0;
for (const name of ASSET_DIRS) {
  const abs = join(pkgRoot, name);
  let entries;
  try {
    entries = walk(abs);
  } catch (err) {
    if (err.code === "ENOENT") {
      throw new Error(
        `${name}/ is missing — run \`node scripts/sync-schemas.mjs\` first (json-schemas/ is generated), ` +
          `and check out the package fully.`
      );
    }
    throw err;
  }
  if (entries.length === 0) throw new Error(`${name}/ is empty; refusing to embed nothing`);
  for (const file of entries) {
    // POSIX separators in the key: the map is read on Windows too, and `join`
    // on the way out puts the platform separator back.
    const key = relative(pkgRoot, file).split(sep).join("/");
    const buf = readFileSync(file);
    rawBytes += buf.length;
    const executable = (statSync(file).mode & 0o111) !== 0;
    files[key] = executable ? { d: buf.toString("base64"), x: 1 } : { d: buf.toString("base64") };
  }
}

const payload = gzipSync(Buffer.from(JSON.stringify(files), "utf8"), { level: 9 });
const base64 = payload.toString("base64");
// Keyed on content, so an upgrade that changes an asset lands in a different
// extraction directory instead of reusing a stale one.
const digest = createHash("sha256").update(payload).digest("hex").slice(0, 16);

const source = `// @generated by scripts/embed-assets.mjs — do not edit.
//
// ${Object.keys(files).length} files from ${ASSET_DIRS.map((d) => `\`${d}/\``).join(", ")},
// gzipped and base64'd so a compiled single-file \`oxyc\` still ships them.
// Regenerate with \`pnpm --filter @oxy-hq/cli build\`.

/** sha256 of the compressed payload, truncated — the extraction cache key. */
export const ASSETS_DIGEST = ${JSON.stringify(digest)};

/** The directories this payload reconstructs, relative to a package root. */
export const ASSET_DIRS = ${JSON.stringify(ASSET_DIRS)} as const;

/** gzip(JSON({ "<path>": { d: base64, x?: 1 } })), base64'd. */
export const ASSETS_GZIP_BASE64 =
  ${JSON.stringify(base64)};
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, source);

const pct = ((payload.length / rawBytes) * 100).toFixed(1);
console.log(
  `embedded ${Object.keys(files).length} files: ` +
    `${(rawBytes / 1024).toFixed(0)} KB raw -> ${(payload.length / 1024).toFixed(0)} KB gzip (${pct}%), ` +
    `digest ${digest}`
);
