#!/usr/bin/env node
/**
 * Emit `src/generated/version.ts` from `package.json`.
 *
 * THE DRIFT THIS REMOVES. `main.ts` carried `.version("0.1.0")` as a literal,
 * so `oxyc --version` was a second copy of the version that nothing kept in
 * step with the manifest — bump `package.json` for a release and the published
 * package reports the old number forever. That is worst for the **standalone
 * binary**, where `--version` is the only way to tell what you have: there is
 * no `package.json` beside it to check, and no npm to ask.
 *
 * GENERATED RATHER THAN IMPORTED, because `import ... from "../package.json"`
 * loses the argument with `tsconfig.json`: `rootDir` is `./src`, so a file
 * above it cannot join the program (`resolveJsonModule` is already on — the
 * blocker is the root, not JSON support). Loosening `rootDir` to admit one
 * constant would put the whole package root in the compiler's scope.
 *
 * READ AT BUILD TIME, not run time, which is the property that matters: the
 * value is baked into `dist/main.mjs` and into each `bun build --compile`
 * binary, so neither has to find a file it may not ship.
 *
 * Runs in `codegen`, alongside `sync-schemas.mjs` and `embed-assets.mjs`, so
 * `prebuild` / `pretest` / `pretypecheck` all get a current value with nobody
 * remembering. `src/generated/` is gitignored for the same reason the schemas
 * are: a committed second copy is the one that silently rots.
 */

import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PKG = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(readFileSync(join(PKG, "package.json"), "utf8"));
const version = manifest.version;

if (typeof version !== "string" || version.length === 0) {
  console.error("package.json has no `version` — nothing to generate.");
  process.exit(1);
}

const out = join(PKG, "src", "generated", "version.ts");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// @generated by scripts/emit-version.mjs — do not edit.
//
// The single source of truth is \`package.json\`. \`oxyc --version\` reads this,
// so a release is one bump in the manifest and nothing else.
export const VERSION = ${JSON.stringify(version)};
`
);

console.log(`version: ${version}`);
