name: Open source onyx in onyx-community
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  move-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        name: Create GitHub App Token
        id: app-token
        with:
          app-id: ${{ vars.ARGO_APP_ID }}
          private-key: ${{ secrets.ARGO_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            onyx-community
            onyx
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: olivr/copybara-action@v1.2.4
        with:
          ssh_key: ${{ secrets.ONYX_SSH_KEY }}
          access_token: ${{ steps.app-token.outputs.token }}
          sot_repo: onyx-hq/onyx
          destination_repo: onyx-hq/onyx-community
          push_exclude: "web-app/**"
          committer: "${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>>"