name: Open source onyx
on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
jobs:
  move-code:
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push' && github.repository == 'onyx-hq/onyx') || (github.event_name == 'pull_request_target' && github.repository == 'onyx-hq/onyx-core') }}
    steps:
      - uses: actions/create-github-app-token@v1
        name: Create GitHub App Token
        id: app-token
        with:
          app-id: ${{ vars.ARGO_APP_ID }}
          private-key: ${{ secrets.ARGO_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            onyx-core
            onyx
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      - uses: luong-komorebi/copybara-action@ft/sync-pull-request-title
        with:
          ssh_key: ${{ secrets.ONYX_SSH_KEY }}
          access_token: ${{ steps.app-token.outputs.token }}
          sot_repo: onyx-hq/onyx
          destination_repo: onyx-hq/onyx-core
          push_exclude: >-
            web-app/**
            crates/onyx-desktop/src/**
            crates/onyx-core/dist
            pnpm-lock.yaml
            pnpm-workspace.yaml
            release-guideline.md
          pr_move: |-
            crates/onyx-desktop/src/lib.rs||oss/lib.rs||**
            pnpm-lock.yaml||oss/pnpm-lock.yaml||**
            crates/onyx-core/dist||oss/dist||**
          committer: "${{ steps.app-token.outputs.app-slug }}[bot] <${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>"
