name: Public Homebrew Update

permissions:
  contents: write

on:
  release:
    types: [created, released, published]

jobs:
  dispatch-event:
    runs-on: ubuntu-latest
    if: github.repository == 'oxy-hq/oxy' && github.event.release.draft == false && github.event.release.prerelease == false
    steps:
      - name: Check if release is latest
        id: check-latest
        run: |
          latest_release=$(
            curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ github.token }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/${{ github.repository }}/releases/latest \
              | jq -r '.tag_name'
          )
          if [[ "${{ github.event.release.tag_name }}" == "$latest_release" ]]; then
            echo "latest=true" >> $GITHUB_OUTPUT
          else
            echo "This release is not the latest. Skipping Homebrew update."
            echo "latest=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger repository_dispatch
        if: steps.check-latest.outputs.latest == 'true'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/oxy-hq/homebrew-oxy/dispatches \
          -d '{"event_type":"oxy_release"}'

      - uses: actions/create-github-app-token@v2
        name: Create GitHub App Token
        if: steps.check-latest.outputs.latest == 'true'
        id: app-token
        with:
          app-id: ${{ vars.ARGO_APP_ID }}
          private-key: ${{ secrets.ARGO_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            oxy
            homebrew-oxy

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: oxy-hq/homebrew-oxy
          event-type: oxy_release
