name: Public Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag or branch to release"
        required: true
        default: ""
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - "docs/**"
env:
  CARGO_TERM_COLOR: always
  MACOSX_DEPLOYMENT_TARGET: "11.0"

defaults:
  run:
    shell: bash

permissions:
  contents: write
  actions: read

jobs:
  build-cli:
    concurrency:
      group: onyx-build-cli-${{ inputs.tag }}-${{ matrix.job.os }}-${{ matrix.job.target }}
      cancel-in-progress: true
    name: Build CLI version ${{ inputs.tag }} for target ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.tag }}

      #-- Create common artifacts folder
      - name: Create artifacts folder
        run: mkdir -p artifacts

      #-- Prep rust
      - name: Prep Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}
      - name: Prep cargo cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: build-cli-${{ matrix.job.os }}-${{ matrix.job.target }}
          cache-all-crates: "true"
      # protobuf is required by lance https://github.com/lancedb/lance/issues/3073
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      #-- Build onyx cli binary
      - name: Build onyx cli
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.job.target }}
          mv target/${{ matrix.job.target }}/release/onyx artifacts/onyx-${{ matrix.job.target }}

      #-- Build json schema
      - name: Generate config schema (once)
        if: ${{ matrix.job.target == 'aarch64-apple-darwin' }}
        run: |
          cargo run --release --target ${{ matrix.job.target }} -- gen-config-schema
          cp -a json-schemas/. artifacts/
          cp Cargo.lock artifacts/

      #-- Build checksum
      - name: Create binary checksum
        run: shasum --algorithm 256 --binary onyx-${{ matrix.job.target }} | tee SHA256SUM-onyx-${{ matrix.job.target }}.txt
        working-directory: artifacts

      #-- Build python lib
      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: "pip"
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: build
          target: ${{ matrix.job.target }}
          args: --release --out dist
          sccache: "true"
          # manylinux: auto
          container: off
          working-directory: crates/onyx-py
      - name: Move wheels
        run: mv crates/onyx-py/dist/* artifacts/

      - name: Copy changelog (once)
        if: ${{ matrix.job.target == 'aarch64-apple-darwin' }}
        run: cp crates/onyx-core/CHANGELOG.md artifacts/

      #-- Upload release artifacts
      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-${{ matrix.job.target }}
          path: |
            artifacts/**/*
          if-no-files-found: error
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [build-cli]
    steps:
      - name: Download release assets from artifact
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: List all artifacts
        run: ls -R ./artifacts
      - name: Combine checksums
        run: cat artifacts/SHA256SUM-onyx-*.txt | tee artifacts/SHA256SUMS.txt
      - name: Ensure binaries are executable
        run: chmod +x artifacts/onyx-*

      - name: Generate release notes
        run: |
          echo "# Changelog" > CHANGELOG.md
          awk '/^## \[/{flag=0} /^## \[${{ inputs.tag }}\]/{flag=1} flag' artifacts/CHANGELOG.md >> CHANGELOG.md
          echo "" >> CHANGELOG.md
          echo "## Checksums" >> CHANGELOG.md
          cat artifacts/SHA256SUMS.txt >> CHANGELOG.md

      - name: Upload files to github release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: true
          tag_name: ${{ inputs.tag }}
          body_path: CHANGELOG.md
          files: artifacts/**/*
