name: Public Release
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to release"
        required: true

jobs:
  release_publicly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      name: Create GitHub App Token
      id: app-token
      with:
        app-id: ${{ vars.ARGO_APP_ID }}
        private-key: ${{ secrets.ARGO_APP_PRIVATE_KEY }}
    - name: Checkout Public Release repo
      uses: actions/checkout@v4
      with:
        repository: onyx-hq/onyx-public-releases
        token: ${{ steps.app-token.outputs.token }}
        persist-credentials: false
    - name: Download release assets from GitHub
      uses: robinraju/release-downloader@v1
      with:
        preRelease: false
        tag: ${{ github.event.release.tag_name || github.event.inputs.tag }}
        zipBall: false
        token: ${{ steps.app-token.outputs.token }}
        fileName: onyx-*
    - name: Get GitHub App User ID
      id: get-user-id
      run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
    - name: Tag the release
      run: |
        git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'
        git tag -a ${{ github.event.release.tag_name || github.event.inputs.tag }} -m "Release ${{ github.event.release.tag_name || github.event.inputs.tag }}"
        git push origin ${{ github.event.release.tag_name || github.event.inputs.tag }}
    - name: Public github release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        tag_name: ${{ github.event.release.tag_name || github.event.inputs.tag }}
        repository: onyx-hq/onyx-public-releases
        files: |
          onyx-*
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
